### ISSUE TITLE
[Feature Request] Docker Health Check Ping support

### ISSUE THREAD

**Issue by ntruhan** [plexguide/Huntarr.io#445]
I run Huntarr inside podman/docker and while I have health checks on most other pods, this one does not.  The /ping url was added so an external app can call it, but the container health check cannot.

Is it possible to add either the net-tools or curl pakage to the image?  I have manually added them via apt-get install from the hunter docker console and net-tools is smaller (providing netstat).  Then in the the yaml, I would use:
    healthcheck:
      interval: 2m
      retries: 10
      test: netstat -ltn | grep -c ":9705" || exit 1
      timeout: 10s

Thank you for the great work you have done with this!

**Comment by Admin9705** [comment]
added the tool - try it now - https://github.com/plexguide/Huntarr.io/releases/tag/6.5.20

**Comment by Krojack** [comment]
I was about to ask for this however I use the follow via curl on all my *arr containers. Curl doesn't seem to be included with the Docker image.

```
    healthcheck:
      test:
      - CMD-SHELL
      - curl --fail http://localhost:9705/ || exit 1
      timeout: 10s
      interval: 1m0s
      retries: 5
      start_period: 20s
```

The netstat would work too but wouldn't jjjjjj
