### ISSUE TITLE
Dropdown lists in "Apps" page are unreadable when selected

### ISSUE THREAD

**Issue by jfrancis2** [plexguide/Huntarr.io#508]
Hi,

Found a UI bug which I've replicated in Firefox and Chromium based browsers. Screenshot at the bottom. 

I did attempt to fix the CSS myself but couldn't quite figure it out. This CSS from `new-style.css` should be handling the look and feel of these dropdowns.

```css
/* Enhanced select boxes */
.setting-item select {
    width: 300px;
    padding: 12px 15px;
    border: 1px solid rgba(90, 109, 137, 0.2);
    border-radius: 8px;
    background: linear-gradient(145deg, rgba(15, 23, 36, 0.7), rgba(22, 30, 45, 0.5));
    color: var(--text-primary);
    font-size: 14px;
    font-weight: 500;
    appearance: none;
    -webkit-appearance: none;
    -moz-appearance: none;
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%235A6D89' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M6 9l6 6 6-6'%3E%3C/path%3E%3C/svg%3E");
    background-repeat: no-repeat;
    background-position: right 15px center;
    transition: all 0.2s ease;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 0 rgba(255, 255, 255, 0.05) inset;
    backdrop-filter: blur(5px);
}

.setting-item select:selected {
    border-color: rgba(52, 152, 219, 0.5);
    box-shadow: 0 0 0 3px rgba(52, 152, 219, 0.15), 0 1px 0 rgba(255, 255, 255, 0.1) inset;
    outline: none;
}

```

 I was able to override some properties but couldn't make the dropdowns have the nice gradient that the other controls have. This was by adding `select` to the same settings for the input boxes, like this (line 5)

```css
/* Enhanced input fields */
.setting-item input[type="text"],
.setting-item input[type="number"],
.setting-item input[type="password"],
.setting-item select {
    width: 300px;
    padding: 12px 15px;
    border: 1px solid rgba(90, 109, 137, 0.2);
    border-radius: 8px;
    background: linear-gradient(145deg, rgba(15, 23, 36, 0.7), rgba(22, 30, 45, 0.5));
    color: var(--text-primary);
    font-size: 14px;
    font-weight: 500;
    transition: all 0.2s ease;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 0 rgba(255, 255, 255, 0.05) inset;
    backdrop-filter: blur(5px);
}
```
That ended up looking like the below, close, but not quite right.

![Image](https://github.com/user-attachments/assets/31d028cf-410d-49a2-8cc3-f7f4122efb95)

The bug:
![Image](https://github.com/user-attachments/assets/9d9dd179-d225-4d1b-8eb9-5e70e41c33dd)

Note that on the same page, the hover behaviour is a bit strange and things move around when you move your mouse across them.
