### ISSUE TITLE
docker healthcheck

### ISSUE THREAD

**Issue by stanthewizzard** [plexguide/Huntarr.io#538]
Hello

Would it be possible to have a healthcheck ?

Thanks

**Comment by sleighton** [comment]
Until curl or wget are added to the image, this healthcheck code should work. Just add to the docker-compose.yaml file for huntarr

```
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n > /dev/tcp/127.0.0.1/9705"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
```
